# Generated by Django 5.2.4 on 2025-09-12 10:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('contenu', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='enquetes/')),
                ('date_publication', models.DateTimeField(default=django.utils.timezone.now)),
                ('categorie', models.CharField(blank=True, max_length=100, null=True)),
                ('a_la_une', models.BooleanField(default=False)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contenu', models.TextField()),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('publie', models.BooleanField(default=True)),
                ('enquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='enquetes.enquete')),
            ],
            options={
                'ordering': ['date_creation'],
            },
        ),
    ]
