# Generated by Django 5.0.10 on 2025-10-05 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icone', models.CharField(help_text="Nom de l’icône (par ex. 'fa-solid fa-code')", max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='expertise_images/')),
            ],
        ),
    ]
