# Generated by Django 5.2.4 on 2025-08-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_customer_contact', models.CharField(max_length=26)),
                ('mail_customer_contact', models.EmailField(max_length=254)),
                ('message_customer_contact', models.TextField()),
            ],
        ),
    ]
