# Generated by Django 5.2.8 on 2025-11-17 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_appelant', models.CharField(max_length=100)),
                ('numero_appelant', models.CharField(max_length=20)),
                ('numero_destinataire', models.CharField(max_length=20)),
                ('date_appel', models.DateTimeField(auto_now_add=True)),
                ('duree_appel', models.DurationField(blank=True, null=True)),
                ('statut_appel', models.CharField(choices=[('entrant', 'Appel entrant'), ('sortant', 'Appel sortant'), ('manque', 'Appel manqué'), ('termine', 'Appel terminé')], default='entrant', max_length=20)),
                ('type_appel', models.CharField(choices=[('audio', 'Audio'), ('video', 'Vidéo')], default='audio', max_length=10)),
            ],
        ),
    ]
