# Generated by Django 5.2.4 on 2025-10-05 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_new_new_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='new',
            options={'ordering': ['-new_publication_date'], 'verbose_name': 'Actualité', 'verbose_name_plural': 'Actualités'},
        ),
        migrations.AddField(
            model_name='new',
            name='new_category',
            field=models.CharField(blank=True, max_length=100, verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='new',
            name='new_excerpt',
            field=models.TextField(blank=True, max_length=300, verbose_name='Résumé'),
        ),
        migrations.AddField(
            model_name='new',
            name='new_slug',
            field=models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='new',
            name='new_status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié')], default='draft', max_length=10, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='new',
            name='new_tags',
            field=models.CharField(blank=True, max_length=200, verbose_name='Mots-clés'),
        ),
        migrations.AddField(
            model_name='new',
            name='new_updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière modification'),
        ),
        migrations.AddField(
            model_name='new',
            name='new_views',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre de vues'),
        ),
        migrations.AlterField(
            model_name='new',
            name='new_author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news', to=settings.AUTH_USER_MODEL, verbose_name='Auteur'),
        ),
        migrations.AlterField(
            model_name='new',
            name='new_content',
            field=models.TextField(verbose_name='Contenu'),
        ),
        migrations.AlterField(
            model_name='new',
            name='new_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/', verbose_name='Image d’illustration'),
        ),
        migrations.AlterField(
            model_name='new',
            name='new_publication_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de publication'),
        ),
        migrations.AlterField(
            model_name='new',
            name='new_title',
            field=models.CharField(max_length=200, unique=True, verbose_name='Titre'),
        ),
    ]
