# Generated by Django 5.2.4 on 2025-10-05 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_new_options_new_new_category_new_new_excerpt_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-comment_publication_date'], 'verbose_name': 'Commentaire', 'verbose_name_plural': 'Commentaires'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Auteur du commentaire'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_content',
            field=models.TextField(verbose_name='Commentaire'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_publication_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date du commentaire'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='new',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.new', verbose_name='Article concerné'),
        ),
    ]
