# Generated by Django 5.2.4 on 2025-08-27 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_cours', models.CharField(max_length=50)),
                ('description_cours', models.CharField(max_length=100)),
                ('images_cours', models.ImageField(default='', upload_to='cours_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_expertise', models.CharField(max_length=50)),
                ('contenu_expertise', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_formation', models.CharField(max_length=50)),
                ('description_formation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Chapitre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_chapitre', models.CharField(max_length=100)),
                ('contenu_chapitre', models.TextField()),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_propos.cours')),
            ],
        ),
        migrations.AddField(
            model_name='cours',
            name='formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_propos.formation'),
        ),
    ]
