# Generated by Django 5.2.4 on 2025-12-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_propos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_mission', models.CharField(max_length=100)),
                ('description_mission', models.TextField()),
                ('icone_fa', models.CharField(default='fas fa-star', help_text='Classe Font Awesome (ex: fas fa-graduation-cap)', max_length=50)),
                ('ordre', models.IntegerField(default=0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mission',
                'verbose_name_plural': 'Missions',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_responsable', models.CharField(max_length=100)),
                ('prenom_responsable', models.CharField(max_length=100)),
                ('photo_responsable', models.ImageField(blank=True, null=True, upload_to='responsables/')),
                ('role_principal', models.CharField(help_text='Ex: Directeur Technique', max_length=100)),
                ('specialite', models.CharField(help_text='Ex: Expert en Développement', max_length=100)),
                ('description', models.TextField()),
                ('ordre', models.IntegerField(default=0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Responsable',
                'verbose_name_plural': 'Responsables',
                'ordering': ['ordre'],
            },
        ),
    ]
