# Generated by Django 5.2.4 on 2025-12-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_propos', '0002_mission_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='couleur_theme',
            field=models.CharField(choices=[('blue', 'Bleu'), ('green', 'Vert'), ('purple', 'Violet'), ('red', 'Rouge'), ('yellow', 'Jaune'), ('pink', 'Rose')], default='blue', help_text='Couleur de la carte', max_length=20),
        ),
    ]
