# Generated by Django 5.2.4 on 2025-09-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='points_cles',
            field=models.TextField(blank=True, null=True),
        ),
    ]
