# Generated by Django 5.2.4 on 2025-08-27 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_produit', models.CharField(max_length=50)),
                ('description_produit', models.TextField()),
                ('version_produit', models.CharField(max_length=20)),
                ('compatibilite_produit', models.CharField(max_length=20)),
                ('licence_produit', models.CharField(max_length=50)),
                ('categorie_produit', models.CharField(max_length=50)),
                ('image_produit', models.ImageField(default='', upload_to='produits_images/')),
            ],
        ),
        migrations.CreateModel(
            name='DemandeDevis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_customer_demane_devis', models.CharField(max_length=26)),
                ('mail_customer_demande_devis', models.EmailField(max_length=254)),
                ('message_demande_devis', models.TextField()),
                ('produi_demande_devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.produit')),
            ],
        ),
    ]
