# Generated by Django 5.2.4 on 2025-08-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caisee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solde_actuel', models.FloatField()),
                ('total_depense_caisse', models.FloatField()),
                ('nombre_transactions_caisse', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_transaction', models.DateTimeField(auto_now_add=True)),
                ('categorie_transaction', models.CharField(max_length=20)),
                ('type_transaction', models.CharField(max_length=10)),
                ('montant_transaction', models.FloatField()),
                ('note_transaction', models.CharField(max_length=20)),
            ],
        ),
    ]
